# NUMPY

In [1]:
import numpy as np                       # numpy is the library which handels nd array

In [2]:
np.__version__

'2.3.5'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(5,dtype=int)                # 1d array

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((2,2))                      # 2d array

array([[0., 0.],
       [0., 0.]])

In [14]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [15]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
np.twos(3)                      # no funtion

AttributeError: module 'numpy' has no attribute 'twos'

In [21]:
np.four(3)                          # no funtion

AttributeError: module 'numpy' has no attribute 'four'

In [22]:
rand(4)                        # not defined

NameError: name 'rand' is not defined

In [23]:
random.rand(4)

NameError: name 'random' is not defined

In [24]:
np.random.rand(4)

array([0.84623298, 0.72528851, 0.05741764, 0.35134782])

In [25]:
np.random.rand(2,2)

array([[0.26654331, 0.15515264],
       [0.0999501 , 0.69776331]])

In [26]:
np.random.randint(3)

1

In [27]:
np.random.randint(0,3)

0

In [28]:
np.random.randint(10,15)

11

In [29]:
np.random.rand(3)

array([0.88155792, 0.60784605, 0.61994013])

In [35]:
np.random.randint(1,5,4)

array([3, 3, 3, 4], dtype=int32)

In [36]:
np.random.randint(1,5,3)

array([4, 3, 2], dtype=int32)

In [37]:
np.random.randint(1,5,2)

array([3, 4], dtype=int32)

In [39]:
np.random.randint(5,2,3)

ValueError: low >= high

In [40]:
np.random.randint(-5,2,3)

array([-2,  1, -2], dtype=int32)

In [43]:
np.random.randint(10,40,(10,10))

array([[37, 28, 14, 25, 14, 28, 34, 37, 17, 33],
       [24, 28, 18, 35, 23, 34, 11, 37, 10, 22],
       [20, 33, 17, 22, 32, 37, 34, 15, 28, 27],
       [18, 26, 35, 33, 10, 21, 20, 37, 11, 22],
       [33, 23, 24, 12, 31, 23, 17, 18, 35, 39],
       [26, 18, 30, 29, 19, 30, 22, 38, 27, 21],
       [36, 35, 38, 23, 37, 21, 13, 27, 25, 21],
       [15, 38, 10, 21, 36, 32, 11, 12, 15, 23],
       [19, 30, 15, 27, 34, 28, 29, 24, 39, 32],
       [27, 15, 32, 17, 22, 17, 32, 17, 31, 17]], dtype=int32)

In [45]:
ri = np.random.randint(10,40,(10,10))
ri

array([[36, 36, 22, 15, 20, 19, 23, 17, 17, 14],
       [10, 36, 30, 11, 19, 16, 37, 26, 17, 16],
       [18, 30, 23, 34, 21, 22, 31, 15, 32, 15],
       [35, 32, 28, 25, 34, 11, 39, 30, 25, 11],
       [20, 28, 33, 18, 31, 34, 19, 26, 35, 31],
       [23, 24, 10, 22, 13, 37, 27, 24, 33, 19],
       [34, 36, 19, 11, 19, 24, 33, 12, 14, 38],
       [25, 16, 17, 24, 29, 35, 32, 32, 17, 32],
       [30, 32, 14, 27, 25, 13, 38, 23, 22, 36],
       [36, 33, 12, 22, 17, 36, 13, 24, 14, 27]], dtype=int32)

In [46]:
 len(ri)    # it will print bydefault 10 rows

10

In [47]:
np.random.randint(10,40,(3,5))

array([[21, 21, 20, 28, 28],
       [12, 20, 18, 35, 17],
       [20, 27, 39, 21, 14]], dtype=int32)

In [48]:
ri.shape     # shape gives the number of rows and column

(10, 10)

In [49]:
id(ri)           # address of the memory location

1854450907920

# Slicing in Numpy

In [53]:
ri[:]

array([[36, 36, 22, 15, 20, 19, 23, 17, 17, 14],
       [10, 36, 30, 11, 19, 16, 37, 26, 17, 16],
       [18, 30, 23, 34, 21, 22, 31, 15, 32, 15],
       [35, 32, 28, 25, 34, 11, 39, 30, 25, 11],
       [20, 28, 33, 18, 31, 34, 19, 26, 35, 31],
       [23, 24, 10, 22, 13, 37, 27, 24, 33, 19],
       [34, 36, 19, 11, 19, 24, 33, 12, 14, 38],
       [25, 16, 17, 24, 29, 35, 32, 32, 17, 32],
       [30, 32, 14, 27, 25, 13, 38, 23, 22, 36],
       [36, 33, 12, 22, 17, 36, 13, 24, 14, 27]], dtype=int32)

In [54]:
ri[1]                     # 1 row of the matrix

array([10, 36, 30, 11, 19, 16, 37, 26, 17, 16], dtype=int32)

In [55]:
ri[0:3]

array([[36, 36, 22, 15, 20, 19, 23, 17, 17, 14],
       [10, 36, 30, 11, 19, 16, 37, 26, 17, 16],
       [18, 30, 23, 34, 21, 22, 31, 15, 32, 15]], dtype=int32)

In [56]:
ri = np.random.randint(10,40,(3,5))
ri

array([[33, 16, 14, 11, 17],
       [35, 34, 39, 37, 29],
       [11, 27, 14, 12, 28]], dtype=int32)

In [57]:
ri[1]

array([35, 34, 39, 37, 29], dtype=int32)

In [59]:
ri[0:3]

array([[33, 16, 14, 11, 17],
       [35, 34, 39, 37, 29],
       [11, 27, 14, 12, 28]], dtype=int32)

In [60]:
ri_1 = np.random.randint(10,40,(10,10))
ri_1

array([[13, 25, 21, 25, 28, 38, 10, 19, 26, 12],
       [20, 15, 15, 29, 31, 39, 25, 10, 20, 29],
       [17, 16, 32, 19, 17, 17, 22, 25, 26, 23],
       [20, 25, 20, 33, 13, 39, 34, 32, 26, 12],
       [15, 16, 37, 25, 22, 32, 33, 13, 15, 33],
       [35, 29, 19, 25, 16, 11, 24, 24, 35, 38],
       [34, 30, 32, 39, 39, 15, 13, 12, 39, 21],
       [26, 24, 16, 24, 39, 17, 38, 35, 20, 10],
       [25, 38, 29, 12, 33, 10, 10, 21, 38, 34],
       [11, 35, 17, 36, 12, 23, 21, 37, 26, 26]], dtype=int32)

In [61]:
ri_1.shape

(10, 10)

In [62]:
ri_1

array([[13, 25, 21, 25, 28, 38, 10, 19, 26, 12],
       [20, 15, 15, 29, 31, 39, 25, 10, 20, 29],
       [17, 16, 32, 19, 17, 17, 22, 25, 26, 23],
       [20, 25, 20, 33, 13, 39, 34, 32, 26, 12],
       [15, 16, 37, 25, 22, 32, 33, 13, 15, 33],
       [35, 29, 19, 25, 16, 11, 24, 24, 35, 38],
       [34, 30, 32, 39, 39, 15, 13, 12, 39, 21],
       [26, 24, 16, 24, 39, 17, 38, 35, 20, 10],
       [25, 38, 29, 12, 33, 10, 10, 21, 38, 34],
       [11, 35, 17, 36, 12, 23, 21, 37, 26, 26]], dtype=int32)

In [63]:
ri_1[:]

array([[13, 25, 21, 25, 28, 38, 10, 19, 26, 12],
       [20, 15, 15, 29, 31, 39, 25, 10, 20, 29],
       [17, 16, 32, 19, 17, 17, 22, 25, 26, 23],
       [20, 25, 20, 33, 13, 39, 34, 32, 26, 12],
       [15, 16, 37, 25, 22, 32, 33, 13, 15, 33],
       [35, 29, 19, 25, 16, 11, 24, 24, 35, 38],
       [34, 30, 32, 39, 39, 15, 13, 12, 39, 21],
       [26, 24, 16, 24, 39, 17, 38, 35, 20, 10],
       [25, 38, 29, 12, 33, 10, 10, 21, 38, 34],
       [11, 35, 17, 36, 12, 23, 21, 37, 26, 26]], dtype=int32)

In [64]:
ri_1[3:8]

array([[20, 25, 20, 33, 13, 39, 34, 32, 26, 12],
       [15, 16, 37, 25, 22, 32, 33, 13, 15, 33],
       [35, 29, 19, 25, 16, 11, 24, 24, 35, 38],
       [34, 30, 32, 39, 39, 15, 13, 12, 39, 21],
       [26, 24, 16, 24, 39, 17, 38, 35, 20, 10]], dtype=int32)

In [66]:
print(ri_1[3,8])

26


In [68]:
ri_1[-5]

array([35, 29, 19, 25, 16, 11, 24, 24, 35, 38], dtype=int32)

In [70]:
print(ri_1[-5,-3])

24


In [72]:
ri_1[::3]

array([[13, 25, 21, 25, 28, 38, 10, 19, 26, 12],
       [20, 25, 20, 33, 13, 39, 34, 32, 26, 12],
       [34, 30, 32, 39, 39, 15, 13, 12, 39, 21],
       [11, 35, 17, 36, 12, 23, 21, 37, 26, 26]], dtype=int32)

In [73]:
ri_1[::-1]   # print the array in reverse

array([[11, 35, 17, 36, 12, 23, 21, 37, 26, 26],
       [25, 38, 29, 12, 33, 10, 10, 21, 38, 34],
       [26, 24, 16, 24, 39, 17, 38, 35, 20, 10],
       [34, 30, 32, 39, 39, 15, 13, 12, 39, 21],
       [35, 29, 19, 25, 16, 11, 24, 24, 35, 38],
       [15, 16, 37, 25, 22, 32, 33, 13, 15, 33],
       [20, 25, 20, 33, 13, 39, 34, 32, 26, 12],
       [17, 16, 32, 19, 17, 17, 22, 25, 26, 23],
       [20, 15, 15, 29, 31, 39, 25, 10, 20, 29],
       [13, 25, 21, 25, 28, 38, 10, 19, 26, 12]], dtype=int32)

In [74]:
ri_1

array([[13, 25, 21, 25, 28, 38, 10, 19, 26, 12],
       [20, 15, 15, 29, 31, 39, 25, 10, 20, 29],
       [17, 16, 32, 19, 17, 17, 22, 25, 26, 23],
       [20, 25, 20, 33, 13, 39, 34, 32, 26, 12],
       [15, 16, 37, 25, 22, 32, 33, 13, 15, 33],
       [35, 29, 19, 25, 16, 11, 24, 24, 35, 38],
       [34, 30, 32, 39, 39, 15, 13, 12, 39, 21],
       [26, 24, 16, 24, 39, 17, 38, 35, 20, 10],
       [25, 38, 29, 12, 33, 10, 10, 21, 38, 34],
       [11, 35, 17, 36, 12, 23, 21, 37, 26, 26]], dtype=int32)

In [75]:
ri_1[::-5]

array([[11, 35, 17, 36, 12, 23, 21, 37, 26, 26],
       [15, 16, 37, 25, 22, 32, 33, 13, 15, 33]], dtype=int32)

In [76]:
ri_1[2]    # it print second row

array([17, 16, 32, 19, 17, 17, 22, 25, 26, 23], dtype=int32)

In [77]:
print(ri_1[2])
print(ri_1[:,2])

[17 16 32 19 17 17 22 25 26 23]
[21 15 32 20 37 19 32 16 29 17]


In [78]:
print(ri_1[:,2])    # it prints columns

[21 15 32 20 37 19 32 16 29 17]


In [79]:
print(ri_1[:,8])

[26 20 26 26 15 35 39 20 38 26]


In [80]:
print(ri_1[:,-8])

[21 15 32 20 37 19 32 16 29 17]


In [81]:
ri_1

array([[13, 25, 21, 25, 28, 38, 10, 19, 26, 12],
       [20, 15, 15, 29, 31, 39, 25, 10, 20, 29],
       [17, 16, 32, 19, 17, 17, 22, 25, 26, 23],
       [20, 25, 20, 33, 13, 39, 34, 32, 26, 12],
       [15, 16, 37, 25, 22, 32, 33, 13, 15, 33],
       [35, 29, 19, 25, 16, 11, 24, 24, 35, 38],
       [34, 30, 32, 39, 39, 15, 13, 12, 39, 21],
       [26, 24, 16, 24, 39, 17, 38, 35, 20, 10],
       [25, 38, 29, 12, 33, 10, 10, 21, 38, 34],
       [11, 35, 17, 36, 12, 23, 21, 37, 26, 26]], dtype=int32)

In [83]:
print(ri_1[0:3,0:3])

[[13 25 21]
 [20 15 15]
 [17 16 32]]


In [84]:
print(ri_1[2:4,4:7])

[[17 17 22]
 [13 39 34]]


 # Numpy masking or filter

In [91]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [92]:
id(mat)

1854455136592

In [93]:
mat.shape

(10, 10)

In [94]:
mat < 50    # it prints true and false

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [95]:
mat[mat < 50]      # its print the values which are less than 50

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [96]:
mat[mat <= 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [97]:
mat[mat !=50]     # its print all the values except 50

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [102]:
mat[mat > 50]      # it prints the value which are greater than 50

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])