#range

In [4]:
range(5)

range(0, 5)

In [5]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [7]:
for i in (range(0,5)):
    print(i)

0
1
2
3
4


In [8]:
range(10,20)

range(10, 20)

In [10]:
list(range(10,20))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [11]:
list(range(0,20,5))

[0, 5, 10, 15]

In [12]:
range(0,10,2,3)                           # range expect only 3 arguments

TypeError: range expected at most 3 arguments, got 4

# numpy

In [13]:
import numpy as np

In [14]:
np.__version__

'2.3.5'

In [15]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [16]:
type(my_list)

list

In [17]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr

array([0, 1, 2, 3, 4, 5])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [25]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [26]:
np.zeros((22),dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [1]:
np.twos(3)        #no funtion

NameError: name 'np' is not defined

In [2]:
np.random.rand(4)

NameError: name 'np' is not defined